// packages/create-fate/templates/fate/http/client/pages/index.tsx
import Stack, { VStack } from '@nkzw/stack';
import { ConnectionRef, useListView, useRequest } from 'react-fate';
import cx from '../src/lib/cx.tsx';
import { Button } from '../src/ui/Button.tsx';
import Card from '../src/ui/Card.tsx';
import H2 from '../src/ui/H2.tsx';
import Link from '../src/ui/Link.tsx';
import { PostCard, PostView } from '../src/ui/PostCard.tsx';
import Section from '../src/ui/Section.tsx';
import UserCard, { UserView } from '../src/ui/UserCard.tsx';

const PostConnectionView = {
  args: { first: 3 },
  items: {
    node: PostView,
  },
  pagination: {
    hasNext: true,
  },
};

const PostFeed = ({ posts: postsRef }: { posts: ConnectionRef<'Post'> }) => {
  const [posts, loadNext] = useListView(PostConnectionView, postsRef);

  return posts.length ? (
    <VStack gap={16}>
      <H2 className="pl-5">
        <fbt desc="Latest posts header">Latest posts</fbt>
      </H2>
      <VStack gap={32}>
        {posts.map(({ node }) => (
          <PostCard key={node.id} post={node} />
        ))}
        {loadNext ? (
          <Stack center>
            <Button onClick={loadNext} variant="ghost">
              <fbt desc="Load more posts button">Load more posts</fbt>
            </Button>
          </Stack>
        ) : null}
      </VStack>
    </VStack>
  ) : null;
};

export default function HomePage() {
  const { posts, viewer } = useRequest({
    posts: { list: PostConnectionView },
    viewer: { view: UserView },
  });

  return (
    <Section gap={32}>
      <div
        className={cx('grid gap-8 lg:items-stretch', viewer?.id ? 'lg:grid-cols-[1.6fr_1fr]' : '')}
      >
        <Card className="border border-white/20 bg-linear-to-r from-blue-500 to-sky-500 text-white dark:from-blue-600 dark:to-sky-600">
          <Stack alignCenter gap={12} wrap>
            <span className="squircle bg-white/20 px-2 py-1 text-xs font-semibold tracking-widest uppercase">
              <span className="lowercase italic">fate</span> demo
            </span>
          </Stack>
          <div className="space-y-3">
            <h1 className="text-3xl leading-tight font-semibold text-balance lg:text-4xl">
              <fbt desc="Description of fate">
                fate is a modern data client for the web inspired by Relay and GraphQL.
              </fbt>
            </h1>
            <p className="text-sm text-white/80 lg:text-base">
              <fbt desc="Tagline for fate">
                fate combines view composition, normalized caching, data masking, Async React
                features, and type-safe data fetching.
              </fbt>
            </p>
          </div>
          <Stack alignCenter gap={12} wrap>
            {!viewer?.id && (
              <>
                <Button asChild size="sm" variant="secondary">
                  <Link className="squircle px-4 py-2 text-sm font-semibold" to="/login">
                    <fbt desc="Login button">Login</fbt>
                  </Link>
                </Button>
                <span className="text-sm text-white/80">
                  <fbt desc="Login button label">Sign in to post comments.</fbt>
                </span>
              </>
            )}
          </Stack>
        </Card>
        {viewer?.id && <UserCard user={viewer} />}
      </div>
      <PostFeed posts={posts} />
    </Section>
  );
}

// packages/create-fate/templates/fate/_shared/vue-app/pages/index.vue
<script setup lang="ts">
import { useListView, useRequest } from 'vue-fate';
import { PostView, UserView } from '../src/fateViews.ts';
import Button from '../src/ui/Button.vue';
import Card from '../src/ui/Card.vue';
import PostCard from '../src/ui/PostCard.vue';
import Section from '../src/ui/Section.vue';
import UserCard from '../src/ui/UserCard.vue';

const PostConnectionView = {
  args: { first: 10 },
  items: {
    node: PostView,
  },
  pagination: {
    hasNext: true,
  },
};

const request = useRequest({
  posts: { list: PostConnectionView },
  viewer: { view: UserView },
});
const { posts: postsRef, viewer } = await request.ready();
const [posts, loadNext] = useListView(PostConnectionView, postsRef);
</script>

<template>
  <Section :gap="32">
    <div class="grid gap-8 lg:grid-cols-[1.6fr_1fr] lg:items-stretch">
      <Card class="border border-white/20 bg-linear-to-r from-blue-500 to-sky-500 text-white">
        <div class="space-y-3">
          <p class="text-xs font-semibold tracking-widest uppercase">
            <span class="lowercase italic">fate</span> demo
          </p>
          <h1 class="text-3xl leading-tight font-semibold text-balance lg:text-4xl">
            fate is a modern data client for the web inspired by Relay and GraphQL.
          </h1>
          <p class="text-sm text-white/80 lg:text-base">
            This template uses Vue-native fate composables, normalized caching, data masking, and
            type-safe data fetching.
          </p>
        </div>
      </Card>
      <UserCard v-if="viewer" :viewer="viewer" />
    </div>
    <div v-if="posts.length" class="flex flex-col gap-4">
      <h2 class="pl-5 text-2xl font-semibold tracking-tight">Latest posts</h2>
      <div class="flex flex-col gap-4">
        <PostCard v-for="{ node } in posts" :key="node.id" :post="node" />
      </div>
      <div v-if="loadNext" class="flex justify-center">
        <Button :action="loadNext" variant="ghost">Load more posts</Button>
      </div>
    </div>
  </Section>
</template>
